T9497b-run: Exception:

T9497b-run.hs:2:8: error: [GHC-88464]
    • Found hole: _main :: IO ()
      Or perhaps ‘_main’ is mis-spelled, or not in scope
    • In an equation for ‘main’: main = _main
    • Relevant bindings include
        main :: IO () (bound at T9497b-run.hs:2:1)
      Valid hole fits include
        main :: IO () (bound at T9497b-run.hs:2:1)
        readLn :: forall a. Read a => IO a
          with readLn @()
          (imported from ‘Prelude’ at T9497b-run.hs:1:1
           (and originally defined in ‘GHC.Internal.System.IO’))
        mempty :: forall a. Monoid a => a
          with mempty @(IO ())
          (imported from ‘Prelude’ at T9497b-run.hs:1:1
           (and originally defined in ‘GHC.Internal.Base’))
(deferred type error)

Package: ghc-internal
Module: GHC.Internal.Control.Exception.Base
Type: TypeError

HasCallStack backtrace:
    collectBacktraces, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:92:13 in ghc-internal:GHC.Internal.Exception
    toExceptionWithBacktrace, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:84:32 in ghc-internal:GHC.Internal.Exception
    throw, called at libraries/ghc-internal/src/GHC/Internal/Control/Exception/Base.hs:423:30 in ghc-internal:GHC.Internal.Control.Exception.Base



