T16066: Uncaught exception ghc-internal:GHC.Internal.Exception.ErrorCall:

exit never happens

HasCallStack backtrace:
  error, called at T16066.hs:27:3 in main:Main

